package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Accion generated by hbm2java
 */
public class Accion implements java.io.Serializable {

	private int idAccion;
	private EstadoAccion estadoAccion;
	private Socio socio;
	private float valor;
	private Set<Venta> ventas = new HashSet<Venta>(0);
	private Set<Desvinculacion> desvinculacions = new HashSet<Desvinculacion>(0);

	public Accion() {
	}

	public Accion(int idAccion, EstadoAccion estadoAccion, Socio socio,
			float valor) {
		this.idAccion = idAccion;
		this.estadoAccion = estadoAccion;
		this.socio = socio;
		this.valor = valor;
	}

	public Accion(int idAccion, EstadoAccion estadoAccion, Socio socio,
			float valor, Set<Venta> ventas, Set<Desvinculacion> desvinculacions) {
		this.idAccion = idAccion;
		this.estadoAccion = estadoAccion;
		this.socio = socio;
		this.valor = valor;
		this.ventas = ventas;
		this.desvinculacions = desvinculacions;
	}

	public int getIdAccion() {
		return this.idAccion;
	}

	public void setIdAccion(int idAccion) {
		this.idAccion = idAccion;
	}

	public EstadoAccion getEstadoAccion() {
		return this.estadoAccion;
	}

	public void setEstadoAccion(EstadoAccion estadoAccion) {
		this.estadoAccion = estadoAccion;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

	public Set<Desvinculacion> getDesvinculacions() {
		return this.desvinculacions;
	}

	public void setDesvinculacions(Set<Desvinculacion> desvinculacions) {
		this.desvinculacions = desvinculacions;
	}

}
