package modelos;

// Generated 25/02/2016 12:54:56 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad implements java.io.Serializable {

	private int idActividad;
	private Evento evento;
	private TipoActividad tipoActividad;
	private String descripcion;
	private String condicion;
	private boolean activo;
	private Set<ProveedorActividad> proveedorActividads = new HashSet<ProveedorActividad>(
			0);

	public Actividad() {
	}

	public Actividad(int idActividad, Evento evento,
			TipoActividad tipoActividad, String descripcion, String condicion,
			boolean activo) {
		this.idActividad = idActividad;
		this.evento = evento;
		this.tipoActividad = tipoActividad;
		this.descripcion = descripcion;
		this.condicion = condicion;
		this.activo = activo;
	}

	public Actividad(int idActividad, Evento evento,
			TipoActividad tipoActividad, String descripcion, String condicion,
			boolean activo, Set<ProveedorActividad> proveedorActividads) {
		this.idActividad = idActividad;
		this.evento = evento;
		this.tipoActividad = tipoActividad;
		this.descripcion = descripcion;
		this.condicion = condicion;
		this.activo = activo;
		this.proveedorActividads = proveedorActividads;
	}

	public int getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(int idActividad) {
		this.idActividad = idActividad;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public TipoActividad getTipoActividad() {
		return this.tipoActividad;
	}

	public void setTipoActividad(TipoActividad tipoActividad) {
		this.tipoActividad = tipoActividad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCondicion() {
		return this.condicion;
	}

	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<ProveedorActividad> getProveedorActividads() {
		return this.proveedorActividads;
	}

	public void setProveedorActividads(
			Set<ProveedorActividad> proveedorActividads) {
		this.proveedorActividads = proveedorActividads;
	}

}
