package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

/**
 * ActividadEvento generated by hbm2java
 */
public class ActividadEvento implements java.io.Serializable {

	private int idActividadEvento;
	private Actividad actividad;
	private Evento evento;

	public ActividadEvento() {
	}

	public ActividadEvento(int idActividadEvento, Actividad actividad,
			Evento evento) {
		this.idActividadEvento = idActividadEvento;
		this.actividad = actividad;
		this.evento = evento;
	}

	public int getIdActividadEvento() {
		return this.idActividadEvento;
	}

	public void setIdActividadEvento(int idActividadEvento) {
		this.idActividadEvento = idActividadEvento;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

}
