package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad implements java.io.Serializable {

	private int idActividad;
	private TipoActividad tipoActividad;
	private String descripcion;
	private String condicion;
	private Set<ProveedorActividad> proveedorActividads = new HashSet<ProveedorActividad>(
			0);
	private Set<ActividadInstalacion> actividadInstalacions = new HashSet<ActividadInstalacion>(
			0);
	private Set<ActividadEvento> actividadEventos = new HashSet<ActividadEvento>(
			0);

	public Actividad() {
	}

	public Actividad(int idActividad, TipoActividad tipoActividad,
			String descripcion, String condicion) {
		this.idActividad = idActividad;
		this.tipoActividad = tipoActividad;
		this.descripcion = descripcion;
		this.condicion = condicion;
	}

	public Actividad(int idActividad, TipoActividad tipoActividad,
			String descripcion, String condicion,
			Set<ProveedorActividad> proveedorActividads,
			Set<ActividadInstalacion> actividadInstalacions,
			Set<ActividadEvento> actividadEventos) {
		this.idActividad = idActividad;
		this.tipoActividad = tipoActividad;
		this.descripcion = descripcion;
		this.condicion = condicion;
		this.proveedorActividads = proveedorActividads;
		this.actividadInstalacions = actividadInstalacions;
		this.actividadEventos = actividadEventos;
	}

	public int getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(int idActividad) {
		this.idActividad = idActividad;
	}

	public TipoActividad getTipoActividad() {
		return this.tipoActividad;
	}

	public void setTipoActividad(TipoActividad tipoActividad) {
		this.tipoActividad = tipoActividad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCondicion() {
		return this.condicion;
	}

	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}

	public Set<ProveedorActividad> getProveedorActividads() {
		return this.proveedorActividads;
	}

	public void setProveedorActividads(
			Set<ProveedorActividad> proveedorActividads) {
		this.proveedorActividads = proveedorActividads;
	}

	public Set<ActividadInstalacion> getActividadInstalacions() {
		return this.actividadInstalacions;
	}

	public void setActividadInstalacions(
			Set<ActividadInstalacion> actividadInstalacions) {
		this.actividadInstalacions = actividadInstalacions;
	}

	public Set<ActividadEvento> getActividadEventos() {
		return this.actividadEventos;
	}

	public void setActividadEventos(Set<ActividadEvento> actividadEventos) {
		this.actividadEventos = actividadEventos;
	}

}
