package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Afiliado generated by hbm2java
 */
public class Afiliado implements java.io.Serializable {

	private int idAfilado;
	private Persona persona;
	private Socio socio;
	private TipoAfiliado tipoAfiliado;
	private String nroCarnet;
	private Set<Visita> visitas = new HashSet<Visita>(0);

	public Afiliado() {
	}

	public Afiliado(int idAfilado, Persona persona, Socio socio,
			TipoAfiliado tipoAfiliado, String nroCarnet) {
		this.idAfilado = idAfilado;
		this.persona = persona;
		this.socio = socio;
		this.tipoAfiliado = tipoAfiliado;
		this.nroCarnet = nroCarnet;
	}

	public Afiliado(int idAfilado, Persona persona, Socio socio,
			TipoAfiliado tipoAfiliado, String nroCarnet, Set<Visita> visitas) {
		this.idAfilado = idAfilado;
		this.persona = persona;
		this.socio = socio;
		this.tipoAfiliado = tipoAfiliado;
		this.nroCarnet = nroCarnet;
		this.visitas = visitas;
	}

	public int getIdAfilado() {
		return this.idAfilado;
	}

	public void setIdAfilado(int idAfilado) {
		this.idAfilado = idAfilado;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public TipoAfiliado getTipoAfiliado() {
		return this.tipoAfiliado;
	}

	public void setTipoAfiliado(TipoAfiliado tipoAfiliado) {
		this.tipoAfiliado = tipoAfiliado;
	}

	public String getNroCarnet() {
		return this.nroCarnet;
	}

	public void setNroCarnet(String nroCarnet) {
		this.nroCarnet = nroCarnet;
	}

	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

}
