package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler implements java.io.Serializable {

	private int idAlquiler;
	private Archivo archivo;
	private Reservacion reservacion;
	private Date fecha;
	private Date hora;
	private short nroTransaccion;
	private float monto;
	private Set<InvitadoAlquiler> invitadoAlquilers = new HashSet<InvitadoAlquiler>(
			0);

	public Alquiler() {
	}

	public Alquiler(int idAlquiler, Archivo archivo, Reservacion reservacion,
			Date fecha, Date hora, short nroTransaccion, float monto) {
		this.idAlquiler = idAlquiler;
		this.archivo = archivo;
		this.reservacion = reservacion;
		this.fecha = fecha;
		this.hora = hora;
		this.nroTransaccion = nroTransaccion;
		this.monto = monto;
	}

	public Alquiler(int idAlquiler, Archivo archivo, Reservacion reservacion,
			Date fecha, Date hora, short nroTransaccion, float monto,
			Set<InvitadoAlquiler> invitadoAlquilers) {
		this.idAlquiler = idAlquiler;
		this.archivo = archivo;
		this.reservacion = reservacion;
		this.fecha = fecha;
		this.hora = hora;
		this.nroTransaccion = nroTransaccion;
		this.monto = monto;
		this.invitadoAlquilers = invitadoAlquilers;
	}

	public int getIdAlquiler() {
		return this.idAlquiler;
	}

	public void setIdAlquiler(int idAlquiler) {
		this.idAlquiler = idAlquiler;
	}

	public Archivo getArchivo() {
		return this.archivo;
	}

	public void setArchivo(Archivo archivo) {
		this.archivo = archivo;
	}

	public Reservacion getReservacion() {
		return this.reservacion;
	}

	public void setReservacion(Reservacion reservacion) {
		this.reservacion = reservacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public short getNroTransaccion() {
		return this.nroTransaccion;
	}

	public void setNroTransaccion(short nroTransaccion) {
		this.nroTransaccion = nroTransaccion;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public Set<InvitadoAlquiler> getInvitadoAlquilers() {
		return this.invitadoAlquilers;
	}

	public void setInvitadoAlquilers(Set<InvitadoAlquiler> invitadoAlquilers) {
		this.invitadoAlquilers = invitadoAlquilers;
	}

}
