package modelos;

// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler implements java.io.Serializable {

	private int idAlquiler;
	private Reservacion reservacion;
	private TipoPago tipoPago;
	private Date fecha;
	private float monto;
	private boolean activo = true;
	private Set<ArchivoAlquiler> archivoAlquilers = new HashSet<ArchivoAlquiler>(
			0);

	public Alquiler() {
	}

	public Alquiler(int idAlquiler, Reservacion reservacion, TipoPago tipoPago,
			Date fecha, float monto, boolean activo) {
		this.idAlquiler = idAlquiler;
		this.reservacion = reservacion;
		this.tipoPago = tipoPago;
		this.fecha = fecha;
		this.monto = monto;
		this.activo = activo;
	}

	public Alquiler(int idAlquiler, Reservacion reservacion, TipoPago tipoPago,
			Date fecha, float monto, boolean activo,
			Set<ArchivoAlquiler> archivoAlquilers) {
		this.idAlquiler = idAlquiler;
		this.reservacion = reservacion;
		this.tipoPago = tipoPago;
		this.fecha = fecha;
		this.monto = monto;
		this.activo = activo;
		this.archivoAlquilers = archivoAlquilers;
	}

	public int getIdAlquiler() {
		return this.idAlquiler;
	}

	public void setIdAlquiler(int idAlquiler) {
		this.idAlquiler = idAlquiler;
	}

	public Reservacion getReservacion() {
		return this.reservacion;
	}

	public void setReservacion(Reservacion reservacion) {
		this.reservacion = reservacion;
	}

	public TipoPago getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago(TipoPago tipoPago) {
		this.tipoPago = tipoPago;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<ArchivoAlquiler> getArchivoAlquilers() {
		return this.archivoAlquilers;
	}

	public void setArchivoAlquilers(Set<ArchivoAlquiler> archivoAlquilers) {
		this.archivoAlquilers = archivoAlquilers;
	}

}
