package modelos;

// Generated 06/03/2016 06:03:48 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Archivo generated by hbm2java
 */
public class Archivo implements java.io.Serializable {

	private int idArchivo;
	private String url;
	private String nombre;
	private String extension;
	private boolean activo = true;
	private Set<ArchivoAlquiler> archivoAlquilers = new HashSet<ArchivoAlquiler>(
			0);

	public Archivo() {
	}

	public Archivo(int idArchivo, String url, String nombre, String extension,
			boolean activo) {
		this.idArchivo = idArchivo;
		this.url = url;
		this.nombre = nombre;
		this.extension = extension;
		this.activo = activo;
	}

	public Archivo(int idArchivo, String url, String nombre, String extension,
			boolean activo, Set<ArchivoAlquiler> archivoAlquilers) {
		this.idArchivo = idArchivo;
		this.url = url;
		this.nombre = nombre;
		this.extension = extension;
		this.activo = activo;
		this.archivoAlquilers = archivoAlquilers;
	}

	public int getIdArchivo() {
		return this.idArchivo;
	}

	public void setIdArchivo(int idArchivo) {
		this.idArchivo = idArchivo;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<ArchivoAlquiler> getArchivoAlquilers() {
		return this.archivoAlquilers;
	}

	public void setArchivoAlquilers(Set<ArchivoAlquiler> archivoAlquilers) {
		this.archivoAlquilers = archivoAlquilers;
	}

}
