package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Archivo generated by hbm2java
 */
public class Archivo implements java.io.Serializable {

	private int idArchivo;
	private String url;
	private String nombre;
	private String extension;
	private Set<Noticia> noticias = new HashSet<Noticia>(0);
	private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);
	private Set<Club> clubs = new HashSet<Club>(0);
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Archivo() {
	}

	public Archivo(int idArchivo, String url, String nombre, String extension) {
		this.idArchivo = idArchivo;
		this.url = url;
		this.nombre = nombre;
		this.extension = extension;
	}

	public Archivo(int idArchivo, String url, String nombre, String extension,
			Set<Noticia> noticias, Set<Alquiler> alquilers, Set<Club> clubs,
			Set<Persona> personas) {
		this.idArchivo = idArchivo;
		this.url = url;
		this.nombre = nombre;
		this.extension = extension;
		this.noticias = noticias;
		this.alquilers = alquilers;
		this.clubs = clubs;
		this.personas = personas;
	}

	public int getIdArchivo() {
		return this.idArchivo;
	}

	public void setIdArchivo(int idArchivo) {
		this.idArchivo = idArchivo;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public Set<Noticia> getNoticias() {
		return this.noticias;
	}

	public void setNoticias(Set<Noticia> noticias) {
		this.noticias = noticias;
	}

	public Set<Alquiler> getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set<Alquiler> alquilers) {
		this.alquilers = alquilers;
	}

	public Set<Club> getClubs() {
		return this.clubs;
	}

	public void setClubs(Set<Club> clubs) {
		this.clubs = clubs;
	}

	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
