package modelos;

// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1

/**
 * ArchivoAlquiler generated by hbm2java
 */
public class ArchivoAlquiler implements java.io.Serializable {

	private int idArchivoAlquiler;
	private Alquiler alquiler;
	private boolean activo = true;
	private String url;
	private String nombre;
	private String tipoListado;
	private String extension;

	public ArchivoAlquiler() {
	}

	public ArchivoAlquiler(int idArchivoAlquiler, Alquiler alquiler,
			String tipoListado, String url, boolean activo) {
		this.idArchivoAlquiler = idArchivoAlquiler;
		this.alquiler = alquiler;
		this.tipoListado = tipoListado;
		this.activo = activo;
		this.url = url;
	}

	public int getIdArchivoAlquiler() {
		return this.idArchivoAlquiler;
	}

	public void setIdArchivoAlquiler(int idArchivoAlquiler) {
		this.idArchivoAlquiler = idArchivoAlquiler;
	}

	public Alquiler getAlquiler() {
		return this.alquiler;
	}

	public void setAlquiler(Alquiler alquiler) {
		this.alquiler = alquiler;
	}

	public String getTipoListado() {
		return this.tipoListado;
	}

	public void setTipoListado(String tipoListado) {
		this.tipoListado = tipoListado;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getExtension() {
		return extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}	
	

}
