package modelos;

// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1

/**
 * ArchivoAlquiler generated by hbm2java
 */
public class ArchivoAlquiler implements java.io.Serializable {

	private int idArchivoAlquiler;
	private Alquiler alquiler;
	private String url;
	private String nombre;
	private String extension;
	private String tipo;
	private boolean activo;

	public ArchivoAlquiler() {
	}

	public ArchivoAlquiler(int idArchivoAlquiler, Alquiler alquiler,
			String url, String nombre, String extension, String tipo,
			boolean activo) {
		this.idArchivoAlquiler = idArchivoAlquiler;
		this.alquiler = alquiler;
		this.url = url;
		this.nombre = nombre;
		this.extension = extension;
		this.tipo = tipo;
		this.activo = activo;
	}

	public int getIdArchivoAlquiler() {
		return this.idArchivoAlquiler;
	}

	public void setIdArchivoAlquiler(int idArchivoAlquiler) {
		this.idArchivoAlquiler = idArchivoAlquiler;
	}

	public Alquiler getAlquiler() {
		return this.alquiler;
	}

	public void setAlquiler(Alquiler alquiler) {
		this.alquiler = alquiler;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
