package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CalendarioFecha generated by hbm2java
 */
public class CalendarioFecha implements java.io.Serializable {

	private int idCalendarioFecha;
	private Evento evento;
	private Reservacion reservacion;
	private String descripcion;
	private Date horaInic;
	private Date horaFin;
	private Date fecha;
	private Set<CalendarioHora> calendarioHoras = new HashSet<CalendarioHora>(0);

	public CalendarioFecha() {
	}

	public CalendarioFecha(int idCalendarioFecha, String descripcion,
			Date horaInic, Date horaFin, Date fecha) {
		this.idCalendarioFecha = idCalendarioFecha;
		this.descripcion = descripcion;
		this.horaInic = horaInic;
		this.horaFin = horaFin;
		this.fecha = fecha;
	}

	public CalendarioFecha(int idCalendarioFecha, Evento evento,
			Reservacion reservacion, String descripcion, Date horaInic,
			Date horaFin, Date fecha, Set<CalendarioHora> calendarioHoras) {
		this.idCalendarioFecha = idCalendarioFecha;
		this.evento = evento;
		this.reservacion = reservacion;
		this.descripcion = descripcion;
		this.horaInic = horaInic;
		this.horaFin = horaFin;
		this.fecha = fecha;
		this.calendarioHoras = calendarioHoras;
	}

	public int getIdCalendarioFecha() {
		return this.idCalendarioFecha;
	}

	public void setIdCalendarioFecha(int idCalendarioFecha) {
		this.idCalendarioFecha = idCalendarioFecha;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Reservacion getReservacion() {
		return this.reservacion;
	}

	public void setReservacion(Reservacion reservacion) {
		this.reservacion = reservacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getHoraInic() {
		return this.horaInic;
	}

	public void setHoraInic(Date horaInic) {
		this.horaInic = horaInic;
	}

	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set<CalendarioHora> getCalendarioHoras() {
		return this.calendarioHoras;
	}

	public void setCalendarioHoras(Set<CalendarioHora> calendarioHoras) {
		this.calendarioHoras = calendarioHoras;
	}

}
