package modelos;

// Generated 08/03/2016 04:38:45 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * CancelacionEvento generated by hbm2java
 */
public class CancelacionEvento implements java.io.Serializable {

	private int idCancelacionEvento;
	private MotivoCancelacion motivoCancelacion;
	private String descipcion;
	private boolean activo = true;
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public CancelacionEvento() {
	}

	public CancelacionEvento(int idCancelacionEvento,
			MotivoCancelacion motivoCancelacion, String descipcion,
			boolean activo) {
		this.idCancelacionEvento = idCancelacionEvento;
		this.motivoCancelacion = motivoCancelacion;
		this.descipcion = descipcion;
		this.activo = activo;
	}

	public CancelacionEvento(int idCancelacionEvento,
			MotivoCancelacion motivoCancelacion, String descipcion,
			boolean activo, Set<Evento> eventos) {
		this.idCancelacionEvento = idCancelacionEvento;
		this.motivoCancelacion = motivoCancelacion;
		this.descipcion = descipcion;
		this.activo = activo;
		this.eventos = eventos;
	}

	public int getIdCancelacionEvento() {
		return this.idCancelacionEvento;
	}

	public void setIdCancelacionEvento(int idCancelacionEvento) {
		this.idCancelacionEvento = idCancelacionEvento;
	}

	public MotivoCancelacion getMotivoCancelacion() {
		return this.motivoCancelacion;
	}

	public void setMotivoCancelacion(MotivoCancelacion motivoCancelacion) {
		this.motivoCancelacion = motivoCancelacion;
	}

	public String getDescipcion() {
		return this.descipcion;
	}

	public void setDescipcion(String descipcion) {
		this.descipcion = descipcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
