package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo implements java.io.Serializable {

	private int idCargo;
	private String descripcion;
	private Set<MiembroJunta> miembroJuntas = new HashSet<MiembroJunta>(0);

	public Cargo() {
	}

	public Cargo(int idCargo, String descripcion) {
		this.idCargo = idCargo;
		this.descripcion = descripcion;
	}

	public Cargo(int idCargo, String descripcion,
			Set<MiembroJunta> miembroJuntas) {
		this.idCargo = idCargo;
		this.descripcion = descripcion;
		this.miembroJuntas = miembroJuntas;
	}

	public int getIdCargo() {
		return this.idCargo;
	}

	public void setIdCargo(int idCargo) {
		this.idCargo = idCargo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<MiembroJunta> getMiembroJuntas() {
		return this.miembroJuntas;
	}

	public void setMiembroJuntas(Set<MiembroJunta> miembroJuntas) {
		this.miembroJuntas = miembroJuntas;
	}

}
