package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Club generated by hbm2java
 */
public class Club implements java.io.Serializable {

	private int idClub;
	private Archivo archivo;
	private String rif;
	private String nombre;
	private String direccion;
	private String telefono;
	private String mision;
	private String vision;
	private String telfAlternativo;
	private String correo;
	private Set<Foto> fotos = new HashSet<Foto>(0);
	private Set<Politica> politicas = new HashSet<Politica>(0);
	private Set<JuntaDirectiva> juntaDirectivas = new HashSet<JuntaDirectiva>(0);
	private Set<RedClub> redClubs = new HashSet<RedClub>(0);

	public Club() {
	}

	public Club(int idClub, Archivo archivo, String rif, String nombre,
			String direccion, String telefono, String mision, String vision,
			String telfAlternativo, String correo) {
		this.idClub = idClub;
		this.archivo = archivo;
		this.rif = rif;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.mision = mision;
		this.vision = vision;
		this.telfAlternativo = telfAlternativo;
		this.correo = correo;
	}

	public Club(int idClub, Archivo archivo, String rif, String nombre,
			String direccion, String telefono, String mision, String vision,
			String telfAlternativo, String correo, Set<Foto> fotos,
			Set<Politica> politicas, Set<JuntaDirectiva> juntaDirectivas,
			Set<RedClub> redClubs) {
		this.idClub = idClub;
		this.archivo = archivo;
		this.rif = rif;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.mision = mision;
		this.vision = vision;
		this.telfAlternativo = telfAlternativo;
		this.correo = correo;
		this.fotos = fotos;
		this.politicas = politicas;
		this.juntaDirectivas = juntaDirectivas;
		this.redClubs = redClubs;
	}

	public int getIdClub() {
		return this.idClub;
	}

	public void setIdClub(int idClub) {
		this.idClub = idClub;
	}

	public Archivo getArchivo() {
		return this.archivo;
	}

	public void setArchivo(Archivo archivo) {
		this.archivo = archivo;
	}

	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getMision() {
		return this.mision;
	}

	public void setMision(String mision) {
		this.mision = mision;
	}

	public String getVision() {
		return this.vision;
	}

	public void setVision(String vision) {
		this.vision = vision;
	}

	public String getTelfAlternativo() {
		return this.telfAlternativo;
	}

	public void setTelfAlternativo(String telfAlternativo) {
		this.telfAlternativo = telfAlternativo;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Set<Foto> getFotos() {
		return this.fotos;
	}

	public void setFotos(Set<Foto> fotos) {
		this.fotos = fotos;
	}

	public Set<Politica> getPoliticas() {
		return this.politicas;
	}

	public void setPoliticas(Set<Politica> politicas) {
		this.politicas = politicas;
	}

	public Set<JuntaDirectiva> getJuntaDirectivas() {
		return this.juntaDirectivas;
	}

	public void setJuntaDirectivas(Set<JuntaDirectiva> juntaDirectivas) {
		this.juntaDirectivas = juntaDirectivas;
	}

	public Set<RedClub> getRedClubs() {
		return this.redClubs;
	}

	public void setRedClubs(Set<RedClub> redClubs) {
		this.redClubs = redClubs;
	}

}
