package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * EstadoEvento generated by hbm2java
 */
public class EstadoEvento implements java.io.Serializable {

	private int idEstadoEvento;
	private String nombre;
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public EstadoEvento() {
	}

	public EstadoEvento(int idEstadoEvento, String nombre) {
		this.idEstadoEvento = idEstadoEvento;
		this.nombre = nombre;
	}

	public EstadoEvento(int idEstadoEvento, String nombre, Set<Evento> eventos) {
		this.idEstadoEvento = idEstadoEvento;
		this.nombre = nombre;
		this.eventos = eventos;
	}

	public int getIdEstadoEvento() {
		return this.idEstadoEvento;
	}

	public void setIdEstadoEvento(int idEstadoEvento) {
		this.idEstadoEvento = idEstadoEvento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
