package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

	private int idEvento;
	private TipoEvento tipoEvento;
	private String descripcion;
	private short visitasEsperadas;
	private String condicionEstado;
	private Date fecha;
	private Date hora;
	private boolean publico;
	private Set<Eventualidad> eventualidads = new HashSet<Eventualidad>(0);
	private Set<Noticia> noticias = new HashSet<Noticia>(0);
	private Set<PreferenciaEvento> preferenciaEventos = new HashSet<PreferenciaEvento>(
			0);
	private Set<VisitaEvento> visitaEventos = new HashSet<VisitaEvento>(0);
	private Set<PartocinanteEvento> partocinanteEventos = new HashSet<PartocinanteEvento>(
			0);
	private Set<CalendarioFecha> calendarioFechas = new HashSet<CalendarioFecha>(
			0);
	private Set<ActividadEvento> actividadEventos = new HashSet<ActividadEvento>(
			0);

	public Evento() {
	}

	public Evento(int idEvento, TipoEvento tipoEvento, String descripcion,
			short visitasEsperadas, String condicionEstado, Date fecha,
			Date hora, boolean publico) {
		this.idEvento = idEvento;
		this.tipoEvento = tipoEvento;
		this.descripcion = descripcion;
		this.visitasEsperadas = visitasEsperadas;
		this.condicionEstado = condicionEstado;
		this.fecha = fecha;
		this.hora = hora;
		this.publico = publico;
	}

	public Evento(int idEvento, TipoEvento tipoEvento, String descripcion,
			short visitasEsperadas, String condicionEstado, Date fecha,
			Date hora, boolean publico, Set<Eventualidad> eventualidads,
			Set<Noticia> noticias, Set<PreferenciaEvento> preferenciaEventos,
			Set<VisitaEvento> visitaEventos,
			Set<PartocinanteEvento> partocinanteEventos,
			Set<CalendarioFecha> calendarioFechas,
			Set<ActividadEvento> actividadEventos) {
		this.idEvento = idEvento;
		this.tipoEvento = tipoEvento;
		this.descripcion = descripcion;
		this.visitasEsperadas = visitasEsperadas;
		this.condicionEstado = condicionEstado;
		this.fecha = fecha;
		this.hora = hora;
		this.publico = publico;
		this.eventualidads = eventualidads;
		this.noticias = noticias;
		this.preferenciaEventos = preferenciaEventos;
		this.visitaEventos = visitaEventos;
		this.partocinanteEventos = partocinanteEventos;
		this.calendarioFechas = calendarioFechas;
		this.actividadEventos = actividadEventos;
	}

	public int getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(int idEvento) {
		this.idEvento = idEvento;
	}

	public TipoEvento getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(TipoEvento tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public short getVisitasEsperadas() {
		return this.visitasEsperadas;
	}

	public void setVisitasEsperadas(short visitasEsperadas) {
		this.visitasEsperadas = visitasEsperadas;
	}

	public String getCondicionEstado() {
		return this.condicionEstado;
	}

	public void setCondicionEstado(String condicionEstado) {
		this.condicionEstado = condicionEstado;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public boolean isPublico() {
		return this.publico;
	}

	public void setPublico(boolean publico) {
		this.publico = publico;
	}

	public Set<Eventualidad> getEventualidads() {
		return this.eventualidads;
	}

	public void setEventualidads(Set<Eventualidad> eventualidads) {
		this.eventualidads = eventualidads;
	}

	public Set<Noticia> getNoticias() {
		return this.noticias;
	}

	public void setNoticias(Set<Noticia> noticias) {
		this.noticias = noticias;
	}

	public Set<PreferenciaEvento> getPreferenciaEventos() {
		return this.preferenciaEventos;
	}

	public void setPreferenciaEventos(Set<PreferenciaEvento> preferenciaEventos) {
		this.preferenciaEventos = preferenciaEventos;
	}

	public Set<VisitaEvento> getVisitaEventos() {
		return this.visitaEventos;
	}

	public void setVisitaEventos(Set<VisitaEvento> visitaEventos) {
		this.visitaEventos = visitaEventos;
	}

	public Set<PartocinanteEvento> getPartocinanteEventos() {
		return this.partocinanteEventos;
	}

	public void setPartocinanteEventos(
			Set<PartocinanteEvento> partocinanteEventos) {
		this.partocinanteEventos = partocinanteEventos;
	}

	public Set<CalendarioFecha> getCalendarioFechas() {
		return this.calendarioFechas;
	}

	public void setCalendarioFechas(Set<CalendarioFecha> calendarioFechas) {
		this.calendarioFechas = calendarioFechas;
	}

	public Set<ActividadEvento> getActividadEventos() {
		return this.actividadEventos;
	}

	public void setActividadEventos(Set<ActividadEvento> actividadEventos) {
		this.actividadEventos = actividadEventos;
	}

}
