package modelos;

// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Eventualidad generated by hbm2java
 */
public class Eventualidad implements java.io.Serializable {

	private int idEventualidad;
	private Instalacion instalacion;
	private Persona persona;
	private TipoEventualidad tipoEventualidad;
	private String descripcion;
	private Date fecha;
	private boolean activo = true;
	private Set<Sancion> sancions = new HashSet<Sancion>(0);

	public Eventualidad() {
	}

	public Eventualidad(int idEventualidad, Persona persona,
			TipoEventualidad tipoEventualidad, String descripcion, Date fecha,
			boolean activo) {
		this.idEventualidad = idEventualidad;
		this.persona = persona;
		this.tipoEventualidad = tipoEventualidad;
		this.descripcion = descripcion;
		this.fecha = fecha;
		this.activo = activo;
	}

	public Eventualidad(int idEventualidad, Instalacion instalacion,
			Persona persona, TipoEventualidad tipoEventualidad,
			String descripcion, Date fecha, boolean activo,
			Set<Sancion> sancions) {
		this.idEventualidad = idEventualidad;
		this.instalacion = instalacion;
		this.persona = persona;
		this.tipoEventualidad = tipoEventualidad;
		this.descripcion = descripcion;
		this.fecha = fecha;
		this.activo = activo;
		this.sancions = sancions;
	}

	public int getIdEventualidad() {
		return this.idEventualidad;
	}

	public void setIdEventualidad(int idEventualidad) {
		this.idEventualidad = idEventualidad;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public TipoEventualidad getTipoEventualidad() {
		return this.tipoEventualidad;
	}

	public void setTipoEventualidad(TipoEventualidad tipoEventualidad) {
		this.tipoEventualidad = tipoEventualidad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Sancion> getSancions() {
		return this.sancions;
	}

	public void setSancions(Set<Sancion> sancions) {
		this.sancions = sancions;
	}

}
