package modelos;

// Generated 06/03/2016 06:03:48 PM by Hibernate Tools 4.3.1

/**
 * Foto generated by hbm2java
 */
public class Foto implements java.io.Serializable {

	private int idFoto;
	private Club club;
	private Instalacion instalacion;
	private String url;
	private boolean publico;
	private boolean activo = true;

	public Foto() {
	}

	public Foto(int idFoto, String url, boolean publico, boolean activo) {
		this.idFoto = idFoto;
		this.url = url;
		this.publico = publico;
		this.activo = activo;
	}

	public Foto(int idFoto, Club club, Instalacion instalacion, String url,
			boolean publico, boolean activo) {
		this.idFoto = idFoto;
		this.club = club;
		this.instalacion = instalacion;
		this.url = url;
		this.publico = publico;
		this.activo = activo;
	}

	public int getIdFoto() {
		return this.idFoto;
	}

	public void setIdFoto(int idFoto) {
		this.idFoto = idFoto;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public boolean isPublico() {
		return this.publico;
	}

	public void setPublico(boolean publico) {
		this.publico = publico;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
