package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Funcion generated by hbm2java
 */
public class Funcion implements java.io.Serializable {

	private int idFuncion;
	private Funcion funcion;
	private String nombre;
	private String pagina;
	private int iconUri;
	private String clase;
	private Set<Funcion> funcions = new HashSet<Funcion>(0);
	private Set<FuncionGrupo> funcionGrupos = new HashSet<FuncionGrupo>(0);

	public Funcion() {
	}

	public Funcion(int idFuncion, Funcion funcion, String nombre,
			String pagina, int iconUri, String clase) {
		this.idFuncion = idFuncion;
		this.funcion = funcion;
		this.nombre = nombre;
		this.pagina = pagina;
		this.iconUri = iconUri;
		this.clase = clase;
	}

	public Funcion(int idFuncion, Funcion funcion, String nombre,
			String pagina, int iconUri, String clase, Set<Funcion> funcions,
			Set<FuncionGrupo> funcionGrupos) {
		this.idFuncion = idFuncion;
		this.funcion = funcion;
		this.nombre = nombre;
		this.pagina = pagina;
		this.iconUri = iconUri;
		this.clase = clase;
		this.funcions = funcions;
		this.funcionGrupos = funcionGrupos;
	}

	public int getIdFuncion() {
		return this.idFuncion;
	}

	public void setIdFuncion(int idFuncion) {
		this.idFuncion = idFuncion;
	}

	public Funcion getFuncion() {
		return this.funcion;
	}

	public void setFuncion(Funcion funcion) {
		this.funcion = funcion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPagina() {
		return this.pagina;
	}

	public void setPagina(String pagina) {
		this.pagina = pagina;
	}

	public int getIconUri() {
		return this.iconUri;
	}

	public void setIconUri(int iconUri) {
		this.iconUri = iconUri;
	}

	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

	public Set<Funcion> getFuncions() {
		return this.funcions;
	}

	public void setFuncions(Set<Funcion> funcions) {
		this.funcions = funcions;
	}

	public Set<FuncionGrupo> getFuncionGrupos() {
		return this.funcionGrupos;
	}

	public void setFuncionGrupos(Set<FuncionGrupo> funcionGrupos) {
		this.funcionGrupos = funcionGrupos;
	}

}
