package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

/**
 * FuncionGrupo generated by hbm2java
 */
public class FuncionGrupo implements java.io.Serializable {

	private int idFuncionGrupo;
	private Funcion funcion;
	private Grupo grupo;

	public FuncionGrupo() {
	}

	public FuncionGrupo(int idFuncionGrupo, Funcion funcion, Grupo grupo) {
		this.idFuncionGrupo = idFuncionGrupo;
		this.funcion = funcion;
		this.grupo = grupo;
	}

	public int getIdFuncionGrupo() {
		return this.idFuncionGrupo;
	}

	public void setIdFuncionGrupo(int idFuncionGrupo) {
		this.idFuncionGrupo = idFuncionGrupo;
	}

	public Funcion getFuncion() {
		return this.funcion;
	}

	public void setFuncion(Funcion funcion) {
		this.funcion = funcion;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

}
