package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Funcion generated by hbm2java
 */
public class Funcion implements java.io.Serializable {

	private int idFuncion;
	private String nombre;
	private String url;
	private Set<FuncionGrupo> funcionGrupos = new HashSet<FuncionGrupo>(0);

	public Funcion() {
	}

	public Funcion(int idFuncion, String nombre, String url) {
		this.idFuncion = idFuncion;
		this.nombre = nombre;
		this.url = url;
	}

	public Funcion(int idFuncion, String nombre, String url,
			Set<FuncionGrupo> funcionGrupos) {
		this.idFuncion = idFuncion;
		this.nombre = nombre;
		this.url = url;
		this.funcionGrupos = funcionGrupos;
	}

	public int getIdFuncion() {
		return this.idFuncion;
	}

	public void setIdFuncion(int idFuncion) {
		this.idFuncion = idFuncion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Set<FuncionGrupo> getFuncionGrupos() {
		return this.funcionGrupos;
	}

	public void setFuncionGrupos(Set<FuncionGrupo> funcionGrupos) {
		this.funcionGrupos = funcionGrupos;
	}

}
