package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hora generated by hbm2java
 */
public class Hora implements java.io.Serializable {

	private int idHora;
	private Date valorHorario;
	private Set<CalendarioHora> calendarioHoras = new HashSet<CalendarioHora>(0);

	public Hora() {
	}

	public Hora(int idHora, Date valorHorario) {
		this.idHora = idHora;
		this.valorHorario = valorHorario;
	}

	public Hora(int idHora, Date valorHorario,
			Set<CalendarioHora> calendarioHoras) {
		this.idHora = idHora;
		this.valorHorario = valorHorario;
		this.calendarioHoras = calendarioHoras;
	}

	public int getIdHora() {
		return this.idHora;
	}

	public void setIdHora(int idHora) {
		this.idHora = idHora;
	}

	public Date getValorHorario() {
		return this.valorHorario;
	}

	public void setValorHorario(Date valorHorario) {
		this.valorHorario = valorHorario;
	}

	public Set<CalendarioHora> getCalendarioHoras() {
		return this.calendarioHoras;
	}

	public void setCalendarioHoras(Set<CalendarioHora> calendarioHoras) {
		this.calendarioHoras = calendarioHoras;
	}

}
