package modelos;

// Generated 25/02/2016 01:23:37 AM by Hibernate Tools 4.3.1

/**
 * IndicadorEvento generated by hbm2java
 */
public class IndicadorEvento implements java.io.Serializable {

	private int idIndicadorEvento;
	private Evento evento;
	private Indicador indicador;
	private short valorEsperado;
	private Short valorReal;
	private boolean activo;

	public IndicadorEvento() {
	}

	public IndicadorEvento(int idIndicadorEvento, Evento evento,
			Indicador indicador, short valorEsperado, boolean activo) {
		this.idIndicadorEvento = idIndicadorEvento;
		this.evento = evento;
		this.indicador = indicador;
		this.valorEsperado = valorEsperado;
		this.activo = activo;
	}

	public IndicadorEvento(int idIndicadorEvento, Evento evento,
			Indicador indicador, short valorEsperado, Short valorReal,
			boolean activo) {
		this.idIndicadorEvento = idIndicadorEvento;
		this.evento = evento;
		this.indicador = indicador;
		this.valorEsperado = valorEsperado;
		this.valorReal = valorReal;
		this.activo = activo;
	}

	public int getIdIndicadorEvento() {
		return this.idIndicadorEvento;
	}

	public void setIdIndicadorEvento(int idIndicadorEvento) {
		this.idIndicadorEvento = idIndicadorEvento;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Indicador getIndicador() {
		return this.indicador;
	}

	public void setIndicador(Indicador indicador) {
		this.indicador = indicador;
	}

	public short getValorEsperado() {
		return this.valorEsperado;
	}

	public void setValorEsperado(short valorEsperado) {
		this.valorEsperado = valorEsperado;
	}

	public Short getValorReal() {
		return this.valorReal;
	}

	public void setValorReal(Short valorReal) {
		this.valorReal = valorReal;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
