package modelos;

// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1

/**
 * InstalacionEvento generated by hbm2java
 */
public class InstalacionEvento implements java.io.Serializable {

	private int idActividadInstalacion;
	private Evento evento;
	private Instalacion instalacion;
	private boolean activo = true;

	public InstalacionEvento() {
	}

	public InstalacionEvento(int idActividadInstalacion, Evento evento,
			Instalacion instalacion, boolean activo) {
		this.idActividadInstalacion = idActividadInstalacion;
		this.evento = evento;
		this.instalacion = instalacion;
		this.activo = activo;
	}

	public int getIdActividadInstalacion() {
		return this.idActividadInstalacion;
	}

	public void setIdActividadInstalacion(int idActividadInstalacion) {
		this.idActividadInstalacion = idActividadInstalacion;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
