package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Instalacion generated by hbm2java
 */
public class Instalacion implements java.io.Serializable {

	private int idInstalacion;
	private TipoInstalacion tipoInstalacion;
	private String descripcion;
	private short capacidad;
	private float precioAlquiler;
	private Set<Reservacion> reservacions = new HashSet<Reservacion>(0);
	private Set<ActividadInstalacion> actividadInstalacions = new HashSet<ActividadInstalacion>(
			0);
	private Set<Foto> fotos = new HashSet<Foto>(0);
	private Set<Eventualidad> eventualidads = new HashSet<Eventualidad>(0);
	private Set<RecursoInstalacion> recursoInstalacions = new HashSet<RecursoInstalacion>(
			0);

	public Instalacion() {
	}

	public Instalacion(int idInstalacion, TipoInstalacion tipoInstalacion,
			String descripcion, short capacidad, float precioAlquiler) {
		this.idInstalacion = idInstalacion;
		this.tipoInstalacion = tipoInstalacion;
		this.descripcion = descripcion;
		this.capacidad = capacidad;
		this.precioAlquiler = precioAlquiler;
	}

	public Instalacion(int idInstalacion, TipoInstalacion tipoInstalacion,
			String descripcion, short capacidad, float precioAlquiler,
			Set<Reservacion> reservacions,
			Set<ActividadInstalacion> actividadInstalacions, Set<Foto> fotos,
			Set<Eventualidad> eventualidads,
			Set<RecursoInstalacion> recursoInstalacions) {
		this.idInstalacion = idInstalacion;
		this.tipoInstalacion = tipoInstalacion;
		this.descripcion = descripcion;
		this.capacidad = capacidad;
		this.precioAlquiler = precioAlquiler;
		this.reservacions = reservacions;
		this.actividadInstalacions = actividadInstalacions;
		this.fotos = fotos;
		this.eventualidads = eventualidads;
		this.recursoInstalacions = recursoInstalacions;
	}

	public int getIdInstalacion() {
		return this.idInstalacion;
	}

	public void setIdInstalacion(int idInstalacion) {
		this.idInstalacion = idInstalacion;
	}

	public TipoInstalacion getTipoInstalacion() {
		return this.tipoInstalacion;
	}

	public void setTipoInstalacion(TipoInstalacion tipoInstalacion) {
		this.tipoInstalacion = tipoInstalacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public short getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(short capacidad) {
		this.capacidad = capacidad;
	}

	public float getPrecioAlquiler() {
		return this.precioAlquiler;
	}

	public void setPrecioAlquiler(float precioAlquiler) {
		this.precioAlquiler = precioAlquiler;
	}

	public Set<Reservacion> getReservacions() {
		return this.reservacions;
	}

	public void setReservacions(Set<Reservacion> reservacions) {
		this.reservacions = reservacions;
	}

	public Set<ActividadInstalacion> getActividadInstalacions() {
		return this.actividadInstalacions;
	}

	public void setActividadInstalacions(
			Set<ActividadInstalacion> actividadInstalacions) {
		this.actividadInstalacions = actividadInstalacions;
	}

	public Set<Foto> getFotos() {
		return this.fotos;
	}

	public void setFotos(Set<Foto> fotos) {
		this.fotos = fotos;
	}

	public Set<Eventualidad> getEventualidads() {
		return this.eventualidads;
	}

	public void setEventualidads(Set<Eventualidad> eventualidads) {
		this.eventualidads = eventualidads;
	}

	public Set<RecursoInstalacion> getRecursoInstalacions() {
		return this.recursoInstalacions;
	}

	public void setRecursoInstalacions(
			Set<RecursoInstalacion> recursoInstalacions) {
		this.recursoInstalacions = recursoInstalacions;
	}

}
