package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JuntaDirectiva generated by hbm2java
 */
public class JuntaDirectiva implements java.io.Serializable {

	private int idJuntaDirectiva;
	private Club club;
	private Date fechaInic;
	private Date fechaFin;
	private Set<MiembroJunta> miembroJuntas = new HashSet<MiembroJunta>(0);

	public JuntaDirectiva() {
	}

	public JuntaDirectiva(int idJuntaDirectiva, Club club, Date fechaInic,
			Date fechaFin) {
		this.idJuntaDirectiva = idJuntaDirectiva;
		this.club = club;
		this.fechaInic = fechaInic;
		this.fechaFin = fechaFin;
	}

	public JuntaDirectiva(int idJuntaDirectiva, Club club, Date fechaInic,
			Date fechaFin, Set<MiembroJunta> miembroJuntas) {
		this.idJuntaDirectiva = idJuntaDirectiva;
		this.club = club;
		this.fechaInic = fechaInic;
		this.fechaFin = fechaFin;
		this.miembroJuntas = miembroJuntas;
	}

	public int getIdJuntaDirectiva() {
		return this.idJuntaDirectiva;
	}

	public void setIdJuntaDirectiva(int idJuntaDirectiva) {
		this.idJuntaDirectiva = idJuntaDirectiva;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public Date getFechaInic() {
		return this.fechaInic;
	}

	public void setFechaInic(Date fechaInic) {
		this.fechaInic = fechaInic;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Set<MiembroJunta> getMiembroJuntas() {
		return this.miembroJuntas;
	}

	public void setMiembroJuntas(Set<MiembroJunta> miembroJuntas) {
		this.miembroJuntas = miembroJuntas;
	}

}
