package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

/**
 * MiembroJunta generated by hbm2java
 */
public class MiembroJunta implements java.io.Serializable {

	private int idJuntaMiembro;
	private Cargo cargo;
	private JuntaDirectiva juntaDirectiva;
	private Persona persona;

	public MiembroJunta() {
	}

	public MiembroJunta(int idJuntaMiembro, Cargo cargo,
			JuntaDirectiva juntaDirectiva, Persona persona) {
		this.idJuntaMiembro = idJuntaMiembro;
		this.cargo = cargo;
		this.juntaDirectiva = juntaDirectiva;
		this.persona = persona;
	}

	public int getIdJuntaMiembro() {
		return this.idJuntaMiembro;
	}

	public void setIdJuntaMiembro(int idJuntaMiembro) {
		this.idJuntaMiembro = idJuntaMiembro;
	}

	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	public JuntaDirectiva getJuntaDirectiva() {
		return this.juntaDirectiva;
	}

	public void setJuntaDirectiva(JuntaDirectiva juntaDirectiva) {
		this.juntaDirectiva = juntaDirectiva;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

}
