package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * MotivoDesvinculacion generated by hbm2java
 */
public class MotivoDesvinculacion implements java.io.Serializable {

	private int idMotivoDesvinculacion;
	private String descripcion;
	private Set<Desvinculacion> desvinculacions = new HashSet<Desvinculacion>(0);

	public MotivoDesvinculacion() {
	}

	public MotivoDesvinculacion(int idMotivoDesvinculacion, String descripcion) {
		this.idMotivoDesvinculacion = idMotivoDesvinculacion;
		this.descripcion = descripcion;
	}

	public MotivoDesvinculacion(int idMotivoDesvinculacion, String descripcion,
			Set<Desvinculacion> desvinculacions) {
		this.idMotivoDesvinculacion = idMotivoDesvinculacion;
		this.descripcion = descripcion;
		this.desvinculacions = desvinculacions;
	}

	public int getIdMotivoDesvinculacion() {
		return this.idMotivoDesvinculacion;
	}

	public void setIdMotivoDesvinculacion(int idMotivoDesvinculacion) {
		this.idMotivoDesvinculacion = idMotivoDesvinculacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Desvinculacion> getDesvinculacions() {
		return this.desvinculacions;
	}

	public void setDesvinculacions(Set<Desvinculacion> desvinculacions) {
		this.desvinculacions = desvinculacions;
	}

}
