package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * MotivoSancion generated by hbm2java
 */
public class MotivoSancion implements java.io.Serializable {

	private int idMotivoSancion;
	private String descripcion;
	private Set<Sancion> sancions = new HashSet<Sancion>(0);

	public MotivoSancion() {
	}

	public MotivoSancion(int idMotivoSancion, String descripcion) {
		this.idMotivoSancion = idMotivoSancion;
		this.descripcion = descripcion;
	}

	public MotivoSancion(int idMotivoSancion, String descripcion,
			Set<Sancion> sancions) {
		this.idMotivoSancion = idMotivoSancion;
		this.descripcion = descripcion;
		this.sancions = sancions;
	}

	public int getIdMotivoSancion() {
		return this.idMotivoSancion;
	}

	public void setIdMotivoSancion(int idMotivoSancion) {
		this.idMotivoSancion = idMotivoSancion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Sancion> getSancions() {
		return this.sancions;
	}

	public void setSancions(Set<Sancion> sancions) {
		this.sancions = sancions;
	}

}
