package modelos;

// Generated 08/03/2016 11:59:00 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * MotivoCancelacion generated by hbm2java
 */
public class MotivoCancelacion implements java.io.Serializable {

	private int idMotivoCancelacion;
	private String descripcion;
	private boolean activo;
	private Set<CancelacionEvento> cancelacionEventos = new HashSet<CancelacionEvento>(
			0);

	public MotivoCancelacion() {
	}

	public MotivoCancelacion(int idMotivoCancelacion, String descripcion,
			boolean activo) {
		this.idMotivoCancelacion = idMotivoCancelacion;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public MotivoCancelacion(int idMotivoCancelacion, String descripcion,
			boolean activo, Set<CancelacionEvento> cancelacionEventos) {
		this.idMotivoCancelacion = idMotivoCancelacion;
		this.descripcion = descripcion;
		this.activo = activo;
		this.cancelacionEventos = cancelacionEventos;
	}

	public int getIdMotivoCancelacion() {
		return this.idMotivoCancelacion;
	}

	public void setIdMotivoCancelacion(int idMotivoCancelacion) {
		this.idMotivoCancelacion = idMotivoCancelacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<CancelacionEvento> getCancelacionEventos() {
		return this.cancelacionEventos;
	}

	public void setCancelacionEventos(Set<CancelacionEvento> cancelacionEventos) {
		this.cancelacionEventos = cancelacionEventos;
	}

}