package modelos;

// Generated 25/02/2016 12:54:56 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * MotivoVenta generated by hbm2java
 */
public class MotivoVenta implements java.io.Serializable {

	private int idMotivoVenta;
	private String descripcion;
	private boolean activo;
	private Set<Venta> ventas = new HashSet<Venta>(0);

	public MotivoVenta() {
	}

	public MotivoVenta(int idMotivoVenta, String descripcion, boolean activo) {
		this.idMotivoVenta = idMotivoVenta;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public MotivoVenta(int idMotivoVenta, String descripcion, boolean activo,
			Set<Venta> ventas) {
		this.idMotivoVenta = idMotivoVenta;
		this.descripcion = descripcion;
		this.activo = activo;
		this.ventas = ventas;
	}

	public int getIdMotivoVenta() {
		return this.idMotivoVenta;
	}

	public void setIdMotivoVenta(int idMotivoVenta) {
		this.idMotivoVenta = idMotivoVenta;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

}
