package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Noticia generated by hbm2java
 */
public class Noticia implements java.io.Serializable {

	private int idNoticia;
	private Archivo archivo;
	private Evento evento;
	private String titulo;
	private String descripcion;
	private boolean condicion;
	private Date caducidad;
	private boolean publico;
	private String enlace;
	private Date fechaCreacion;
	private Set<NoticiaPreferencia> noticiaPreferencias = new HashSet<NoticiaPreferencia>(
			0);

	public Noticia() {
	}

	public Noticia(int idNoticia, Archivo archivo, String descripcion,
			boolean condicion, Date caducidad, boolean publico,
			Date fechaCreacion) {
		this.idNoticia = idNoticia;
		this.archivo = archivo;
		this.descripcion = descripcion;
		this.condicion = condicion;
		this.caducidad = caducidad;
		this.publico = publico;
		this.fechaCreacion = fechaCreacion;
	}

	public Noticia(int idNoticia, Archivo archivo, Evento evento,
			String titulo, String descripcion, boolean condicion,
			Date caducidad, boolean publico, String enlace, Date fechaCreacion,
			Set<NoticiaPreferencia> noticiaPreferencias) {
		this.idNoticia = idNoticia;
		this.archivo = archivo;
		this.evento = evento;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.condicion = condicion;
		this.caducidad = caducidad;
		this.publico = publico;
		this.enlace = enlace;
		this.fechaCreacion = fechaCreacion;
		this.noticiaPreferencias = noticiaPreferencias;
	}

	public int getIdNoticia() {
		return this.idNoticia;
	}

	public void setIdNoticia(int idNoticia) {
		this.idNoticia = idNoticia;
	}

	public Archivo getArchivo() {
		return this.archivo;
	}

	public void setArchivo(Archivo archivo) {
		this.archivo = archivo;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isCondicion() {
		return this.condicion;
	}

	public void setCondicion(boolean condicion) {
		this.condicion = condicion;
	}

	public Date getCaducidad() {
		return this.caducidad;
	}

	public void setCaducidad(Date caducidad) {
		this.caducidad = caducidad;
	}

	public boolean isPublico() {
		return this.publico;
	}

	public void setPublico(boolean publico) {
		this.publico = publico;
	}

	public String getEnlace() {
		return this.enlace;
	}

	public void setEnlace(String enlace) {
		this.enlace = enlace;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set<NoticiaPreferencia> getNoticiaPreferencias() {
		return this.noticiaPreferencias;
	}

	public void setNoticiaPreferencias(
			Set<NoticiaPreferencia> noticiaPreferencias) {
		this.noticiaPreferencias = noticiaPreferencias;
	}

}
