package modelos;

// Generated 25/02/2016 12:54:56 AM by Hibernate Tools 4.3.1

/**
 * PartocinanteEvento generated by hbm2java
 */
public class PartocinanteEvento implements java.io.Serializable {

	private int idPatrocinanteEvento;
	private Evento evento;
	private Patrocinante patrocinante;
	private boolean activo;

	public PartocinanteEvento() {
	}

	public PartocinanteEvento(int idPatrocinanteEvento, Evento evento,
			Patrocinante patrocinante, boolean activo) {
		this.idPatrocinanteEvento = idPatrocinanteEvento;
		this.evento = evento;
		this.patrocinante = patrocinante;
		this.activo = activo;
	}

	public int getIdPatrocinanteEvento() {
		return this.idPatrocinanteEvento;
	}

	public void setIdPatrocinanteEvento(int idPatrocinanteEvento) {
		this.idPatrocinanteEvento = idPatrocinanteEvento;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Patrocinante getPatrocinante() {
		return this.patrocinante;
	}

	public void setPatrocinante(Patrocinante patrocinante) {
		this.patrocinante = patrocinante;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
