package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

/**
 * PartocinanteEvento generated by hbm2java
 */
public class PartocinanteEvento implements java.io.Serializable {

	private int idPatrocinanteActividad;
	private Evento evento;
	private Patrocinante patrocinante;

	public PartocinanteEvento() {
	}

	public PartocinanteEvento(int idPatrocinanteActividad, Evento evento,
			Patrocinante patrocinante) {
		this.idPatrocinanteActividad = idPatrocinanteActividad;
		this.evento = evento;
		this.patrocinante = patrocinante;
	}

	public int getIdPatrocinanteActividad() {
		return this.idPatrocinanteActividad;
	}

	public void setIdPatrocinanteActividad(int idPatrocinanteActividad) {
		this.idPatrocinanteActividad = idPatrocinanteActividad;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Patrocinante getPatrocinante() {
		return this.patrocinante;
	}

	public void setPatrocinante(Patrocinante patrocinante) {
		this.patrocinante = patrocinante;
	}

}
