package modelos;

// Generated 26/02/2016 11:27:56 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Patrocinante generated by hbm2java
 */
public class Patrocinante implements java.io.Serializable {

	private int idPatrocinante;
	private String nombre;
	private String direccion;
	private String telefono;
	private String correo;
	private boolean activo;
	private String rifIdentificador;
	private Set<PartocinanteEvento> partocinanteEventos = new HashSet<PartocinanteEvento>(
			0);

	public Patrocinante() {
	}

	public Patrocinante(int idPatrocinante, String nombre, String direccion,
			String telefono, boolean activo, String rifIdentificador) {
		this.idPatrocinante = idPatrocinante;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.activo = activo;
		this.rifIdentificador = rifIdentificador;
	}

	public Patrocinante(int idPatrocinante, String nombre, String direccion,
			String telefono, String correo, boolean activo,
			String rifIdentificador, Set<PartocinanteEvento> partocinanteEventos) {
		this.idPatrocinante = idPatrocinante;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
		this.activo = activo;
		this.rifIdentificador = rifIdentificador;
		this.partocinanteEventos = partocinanteEventos;
	}

	public int getIdPatrocinante() {
		return this.idPatrocinante;
	}

	public void setIdPatrocinante(int idPatrocinante) {
		this.idPatrocinante = idPatrocinante;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public String getRifIdentificador() {
		return this.rifIdentificador;
	}

	public void setRifIdentificador(String rifIdentificador) {
		this.rifIdentificador = rifIdentificador;
	}

	public Set<PartocinanteEvento> getPartocinanteEventos() {
		return this.partocinanteEventos;
	}

	public void setPartocinanteEventos(
			Set<PartocinanteEvento> partocinanteEventos) {
		this.partocinanteEventos = partocinanteEventos;
	}

}
