package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private int idPersona;
	private Archivo archivo;
	private String identificacion;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private Date fechaNac;
	private String sexo;
	private String correo;
	private short telefono;
	private Short telefonoFijo;
	private String direccion;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);
	private Set<MiembroJunta> miembroJuntas = new HashSet<MiembroJunta>(0);
	private Set<Afiliado> afiliados = new HashSet<Afiliado>(0);
	private Set<RedPersona> redPersonas = new HashSet<RedPersona>(0);
	private Set<Socio> socios = new HashSet<Socio>(0);
	private Set<Eventualidad> eventualidads = new HashSet<Eventualidad>(0);
	private Set<Invitado> invitados = new HashSet<Invitado>(0);
	private Set<Postulado> postulados = new HashSet<Postulado>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<PreferenciaPersona> preferenciaPersonas = new HashSet<PreferenciaPersona>(
			0);

	public Persona() {
	}

	public Persona(int idPersona, Archivo archivo, String primerNombre,
			String primerApellido, Date fechaNac, String sexo, short telefono) {
		this.idPersona = idPersona;
		this.archivo = archivo;
		this.primerNombre = primerNombre;
		this.primerApellido = primerApellido;
		this.fechaNac = fechaNac;
		this.sexo = sexo;
		this.telefono = telefono;
	}

	public Persona(int idPersona, Archivo archivo, String identificacion,
			String primerNombre, String segundoNombre, String primerApellido,
			String segundoApellido, Date fechaNac, String sexo, String correo,
			short telefono, Short telefonoFijo, String direccion,
			Set<Empleado> empleados, Set<MiembroJunta> miembroJuntas,
			Set<Afiliado> afiliados, Set<RedPersona> redPersonas,
			Set<Socio> socios, Set<Eventualidad> eventualidads,
			Set<Invitado> invitados, Set<Postulado> postulados,
			Set<Usuario> usuarios, Set<PreferenciaPersona> preferenciaPersonas) {
		this.idPersona = idPersona;
		this.archivo = archivo;
		this.identificacion = identificacion;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.fechaNac = fechaNac;
		this.sexo = sexo;
		this.correo = correo;
		this.telefono = telefono;
		this.telefonoFijo = telefonoFijo;
		this.direccion = direccion;
		this.empleados = empleados;
		this.miembroJuntas = miembroJuntas;
		this.afiliados = afiliados;
		this.redPersonas = redPersonas;
		this.socios = socios;
		this.eventualidads = eventualidads;
		this.invitados = invitados;
		this.postulados = postulados;
		this.usuarios = usuarios;
		this.preferenciaPersonas = preferenciaPersonas;
	}

	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	public Archivo getArchivo() {
		return this.archivo;
	}

	public void setArchivo(Archivo archivo) {
		this.archivo = archivo;
	}

	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public short getTelefono() {
		return this.telefono;
	}

	public void setTelefono(short telefono) {
		this.telefono = telefono;
	}

	public Short getTelefonoFijo() {
		return this.telefonoFijo;
	}

	public void setTelefonoFijo(Short telefonoFijo) {
		this.telefonoFijo = telefonoFijo;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

	public Set<MiembroJunta> getMiembroJuntas() {
		return this.miembroJuntas;
	}

	public void setMiembroJuntas(Set<MiembroJunta> miembroJuntas) {
		this.miembroJuntas = miembroJuntas;
	}

	public Set<Afiliado> getAfiliados() {
		return this.afiliados;
	}

	public void setAfiliados(Set<Afiliado> afiliados) {
		this.afiliados = afiliados;
	}

	public Set<RedPersona> getRedPersonas() {
		return this.redPersonas;
	}

	public void setRedPersonas(Set<RedPersona> redPersonas) {
		this.redPersonas = redPersonas;
	}

	public Set<Socio> getSocios() {
		return this.socios;
	}

	public void setSocios(Set<Socio> socios) {
		this.socios = socios;
	}

	public Set<Eventualidad> getEventualidads() {
		return this.eventualidads;
	}

	public void setEventualidads(Set<Eventualidad> eventualidads) {
		this.eventualidads = eventualidads;
	}

	public Set<Invitado> getInvitados() {
		return this.invitados;
	}

	public void setInvitados(Set<Invitado> invitados) {
		this.invitados = invitados;
	}

	public Set<Postulado> getPostulados() {
		return this.postulados;
	}

	public void setPostulados(Set<Postulado> postulados) {
		this.postulados = postulados;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public Set<PreferenciaPersona> getPreferenciaPersonas() {
		return this.preferenciaPersonas;
	}

	public void setPreferenciaPersonas(
			Set<PreferenciaPersona> preferenciaPersonas) {
		this.preferenciaPersonas = preferenciaPersonas;
	}

}
