package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

/**
 * Politica generated by hbm2java
 */
public class Politica implements java.io.Serializable {

	private int idPolitica;
	private Club club;
	private TipoPolitica tipoPolitica;
	private String descripcion;
	private Integer frecuencia;
	private Integer cantidadInvitados;
	private String parentesco;

	public Politica() {
	}

	public Politica(int idPolitica, Club club, TipoPolitica tipoPolitica,
			String descripcion) {
		this.idPolitica = idPolitica;
		this.club = club;
		this.tipoPolitica = tipoPolitica;
		this.descripcion = descripcion;
	}

	public Politica(int idPolitica, Club club, TipoPolitica tipoPolitica,
			String descripcion, Integer frecuencia, Integer cantidadInvitados,
			String parentesco) {
		this.idPolitica = idPolitica;
		this.club = club;
		this.tipoPolitica = tipoPolitica;
		this.descripcion = descripcion;
		this.frecuencia = frecuencia;
		this.cantidadInvitados = cantidadInvitados;
		this.parentesco = parentesco;
	}

	public int getIdPolitica() {
		return this.idPolitica;
	}

	public void setIdPolitica(int idPolitica) {
		this.idPolitica = idPolitica;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public TipoPolitica getTipoPolitica() {
		return this.tipoPolitica;
	}

	public void setTipoPolitica(TipoPolitica tipoPolitica) {
		this.tipoPolitica = tipoPolitica;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getFrecuencia() {
		return this.frecuencia;
	}

	public void setFrecuencia(Integer frecuencia) {
		this.frecuencia = frecuencia;
	}

	public Integer getCantidadInvitados() {
		return this.cantidadInvitados;
	}

	public void setCantidadInvitados(Integer cantidadInvitados) {
		this.cantidadInvitados = cantidadInvitados;
	}

	public String getParentesco() {
		return this.parentesco;
	}

	public void setParentesco(String parentesco) {
		this.parentesco = parentesco;
	}

}
