package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

/**
 * Politica generated by hbm2java
 */
public class Politica implements java.io.Serializable {

	private int idPolitica;
	private Club club;
	private String parametro;
	private short valor;

	public Politica() {
	}

	public Politica(int idPolitica, Club club, String parametro, short valor) {
		this.idPolitica = idPolitica;
		this.club = club;
		this.parametro = parametro;
		this.valor = valor;
	}

	public int getIdPolitica() {
		return this.idPolitica;
	}

	public void setIdPolitica(int idPolitica) {
		this.idPolitica = idPolitica;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

	public short getValor() {
		return this.valor;
	}

	public void setValor(short valor) {
		this.valor = valor;
	}

}
