package modelos;

// Generated 26/02/2016 11:27:56 AM by Hibernate Tools 4.3.1

/**
 * Politica generated by hbm2java
 */
public class Politica implements java.io.Serializable {

	private int idPolitica;
	private TipoAfiliado tipoAfiliado;
	private TipoPolitica tipoPolitica;
	private String descripcion;
	private Integer frecuencia;
	private Integer cantidadInvitados;
	private String atributo;
	private boolean activo;

	public Politica() {
	}

	public Politica(int idPolitica, TipoAfiliado tipoAfiliado,
			TipoPolitica tipoPolitica, String descripcion, String atributo,
			boolean activo) {
		this.idPolitica = idPolitica;
		this.tipoAfiliado = tipoAfiliado;
		this.tipoPolitica = tipoPolitica;
		this.descripcion = descripcion;
		this.atributo = atributo;
		this.activo = activo;
	}

	public Politica(int idPolitica, TipoAfiliado tipoAfiliado,
			TipoPolitica tipoPolitica, String descripcion, Integer frecuencia,
			Integer cantidadInvitados, String atributo, boolean activo) {
		this.idPolitica = idPolitica;
		this.tipoAfiliado = tipoAfiliado;
		this.tipoPolitica = tipoPolitica;
		this.descripcion = descripcion;
		this.frecuencia = frecuencia;
		this.cantidadInvitados = cantidadInvitados;
		this.atributo = atributo;
		this.activo = activo;
	}

	public int getIdPolitica() {
		return this.idPolitica;
	}

	public void setIdPolitica(int idPolitica) {
		this.idPolitica = idPolitica;
	}

	public TipoAfiliado getTipoAfiliado() {
		return this.tipoAfiliado;
	}

	public void setTipoAfiliado(TipoAfiliado tipoAfiliado) {
		this.tipoAfiliado = tipoAfiliado;
	}

	public TipoPolitica getTipoPolitica() {
		return this.tipoPolitica;
	}

	public void setTipoPolitica(TipoPolitica tipoPolitica) {
		this.tipoPolitica = tipoPolitica;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getFrecuencia() {
		return this.frecuencia;
	}

	public void setFrecuencia(Integer frecuencia) {
		this.frecuencia = frecuencia;
	}

	public Integer getCantidadInvitados() {
		return this.cantidadInvitados;
	}

	public void setCantidadInvitados(Integer cantidadInvitados) {
		this.cantidadInvitados = cantidadInvitados;
	}

	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
