package modelos;

// Generated 25/02/2016 01:23:37 AM by Hibernate Tools 4.3.1

/**
 * PreferenciaSolicitud generated by hbm2java
 */
public class PreferenciaSolicitud implements java.io.Serializable {

	private int idPreferenciaSolicitud;
	private Preferencia preferencia;
	private short solicitudEventoidSolicitudEvento;
	private boolean activo;

	public PreferenciaSolicitud() {
	}

	public PreferenciaSolicitud(int idPreferenciaSolicitud,
			Preferencia preferencia, short solicitudEventoidSolicitudEvento,
			boolean activo) {
		this.idPreferenciaSolicitud = idPreferenciaSolicitud;
		this.preferencia = preferencia;
		this.solicitudEventoidSolicitudEvento = solicitudEventoidSolicitudEvento;
		this.activo = activo;
	}

	public int getIdPreferenciaSolicitud() {
		return this.idPreferenciaSolicitud;
	}

	public void setIdPreferenciaSolicitud(int idPreferenciaSolicitud) {
		this.idPreferenciaSolicitud = idPreferenciaSolicitud;
	}

	public Preferencia getPreferencia() {
		return this.preferencia;
	}

	public void setPreferencia(Preferencia preferencia) {
		this.preferencia = preferencia;
	}

	public short getSolicitudEventoidSolicitudEvento() {
		return this.solicitudEventoidSolicitudEvento;
	}

	public void setSolicitudEventoidSolicitudEvento(
			short solicitudEventoidSolicitudEvento) {
		this.solicitudEventoidSolicitudEvento = solicitudEventoidSolicitudEvento;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
