package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

/**
 * PreferenciaEvento generated by hbm2java
 */
public class PreferenciaEvento implements java.io.Serializable {

	private int idPreferenciaEvento;
	private Evento evento;
	private Preferencia preferencia;

	public PreferenciaEvento() {
	}

	public PreferenciaEvento(int idPreferenciaEvento, Evento evento,
			Preferencia preferencia) {
		this.idPreferenciaEvento = idPreferenciaEvento;
		this.evento = evento;
		this.preferencia = preferencia;
	}

	public int getIdPreferenciaEvento() {
		return this.idPreferenciaEvento;
	}

	public void setIdPreferenciaEvento(int idPreferenciaEvento) {
		this.idPreferenciaEvento = idPreferenciaEvento;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Preferencia getPreferencia() {
		return this.preferencia;
	}

	public void setPreferencia(Preferencia preferencia) {
		this.preferencia = preferencia;
	}

}
