package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Preferencia generated by hbm2java
 */
public class Preferencia implements java.io.Serializable {

	private int idPreferencia;
	private TipoPreferencia tipoPreferencia;
	private String descripcion;
	private Set<PreferenciaEvento> preferenciaEventos = new HashSet<PreferenciaEvento>(
			0);
	private Set<PreferenciaPersona> preferenciaPersonas = new HashSet<PreferenciaPersona>(
			0);
	private Set<NoticiaPreferencia> noticiaPreferencias = new HashSet<NoticiaPreferencia>(
			0);

	public Preferencia() {
	}

	public Preferencia(int idPreferencia, TipoPreferencia tipoPreferencia,
			String descripcion) {
		this.idPreferencia = idPreferencia;
		this.tipoPreferencia = tipoPreferencia;
		this.descripcion = descripcion;
	}

	public Preferencia(int idPreferencia, TipoPreferencia tipoPreferencia,
			String descripcion, Set<PreferenciaEvento> preferenciaEventos,
			Set<PreferenciaPersona> preferenciaPersonas,
			Set<NoticiaPreferencia> noticiaPreferencias) {
		this.idPreferencia = idPreferencia;
		this.tipoPreferencia = tipoPreferencia;
		this.descripcion = descripcion;
		this.preferenciaEventos = preferenciaEventos;
		this.preferenciaPersonas = preferenciaPersonas;
		this.noticiaPreferencias = noticiaPreferencias;
	}

	public int getIdPreferencia() {
		return this.idPreferencia;
	}

	public void setIdPreferencia(int idPreferencia) {
		this.idPreferencia = idPreferencia;
	}

	public TipoPreferencia getTipoPreferencia() {
		return this.tipoPreferencia;
	}

	public void setTipoPreferencia(TipoPreferencia tipoPreferencia) {
		this.tipoPreferencia = tipoPreferencia;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<PreferenciaEvento> getPreferenciaEventos() {
		return this.preferenciaEventos;
	}

	public void setPreferenciaEventos(Set<PreferenciaEvento> preferenciaEventos) {
		this.preferenciaEventos = preferenciaEventos;
	}

	public Set<PreferenciaPersona> getPreferenciaPersonas() {
		return this.preferenciaPersonas;
	}

	public void setPreferenciaPersonas(
			Set<PreferenciaPersona> preferenciaPersonas) {
		this.preferenciaPersonas = preferenciaPersonas;
	}

	public Set<NoticiaPreferencia> getNoticiaPreferencias() {
		return this.noticiaPreferencias;
	}

	public void setNoticiaPreferencias(
			Set<NoticiaPreferencia> noticiaPreferencias) {
		this.noticiaPreferencias = noticiaPreferencias;
	}

}
