package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

/**
 * ProveedorActividad generated by hbm2java
 */
public class ProveedorActividad implements java.io.Serializable {

	private int idProveedorActividad;
	private Actividad actividad;
	private Proveedor proveedor;

	public ProveedorActividad() {
	}

	public ProveedorActividad(int idProveedorActividad, Actividad actividad,
			Proveedor proveedor) {
		this.idProveedorActividad = idProveedorActividad;
		this.actividad = actividad;
		this.proveedor = proveedor;
	}

	public int getIdProveedorActividad() {
		return this.idProveedorActividad;
	}

	public void setIdProveedorActividad(int idProveedorActividad) {
		this.idProveedorActividad = idProveedorActividad;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

}
