package modelos;

// Generated 25/02/2016 01:23:37 AM by Hibernate Tools 4.3.1

/**
 * ProveedorActividad generated by hbm2java
 */
public class ProveedorActividad implements java.io.Serializable {

	private int idProveedorActividad;
	private Actividad actividad;
	private Proveedor proveedor;
	private String detalle;
	private boolean activo;

	public ProveedorActividad() {
	}

	public ProveedorActividad(int idProveedorActividad, Actividad actividad,
			Proveedor proveedor, boolean activo) {
		this.idProveedorActividad = idProveedorActividad;
		this.actividad = actividad;
		this.proveedor = proveedor;
		this.activo = activo;
	}

	public ProveedorActividad(int idProveedorActividad, Actividad actividad,
			Proveedor proveedor, String detalle, boolean activo) {
		this.idProveedorActividad = idProveedorActividad;
		this.actividad = actividad;
		this.proveedor = proveedor;
		this.detalle = detalle;
		this.activo = activo;
	}

	public int getIdProveedorActividad() {
		return this.idProveedorActividad;
	}

	public void setIdProveedorActividad(int idProveedorActividad) {
		this.idProveedorActividad = idProveedorActividad;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
