package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso implements java.io.Serializable {

	private int idRecurso;
	private String descripcion;
	private Set<RecursoInstalacion> recursoInstalacions = new HashSet<RecursoInstalacion>(
			0);

	public Recurso() {
	}

	public Recurso(int idRecurso, String descripcion) {
		this.idRecurso = idRecurso;
		this.descripcion = descripcion;
	}

	public Recurso(int idRecurso, String descripcion,
			Set<RecursoInstalacion> recursoInstalacions) {
		this.idRecurso = idRecurso;
		this.descripcion = descripcion;
		this.recursoInstalacions = recursoInstalacions;
	}

	public int getIdRecurso() {
		return this.idRecurso;
	}

	public void setIdRecurso(int idRecurso) {
		this.idRecurso = idRecurso;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<RecursoInstalacion> getRecursoInstalacions() {
		return this.recursoInstalacions;
	}

	public void setRecursoInstalacions(
			Set<RecursoInstalacion> recursoInstalacions) {
		this.recursoInstalacions = recursoInstalacions;
	}

}
