package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

/**
 * RecursoInstalacion generated by hbm2java
 */
public class RecursoInstalacion implements java.io.Serializable {

	private int idRecursoInstalacion;
	private Instalacion instalacion;
	private Recurso recurso;
	private short cantidad;

	public RecursoInstalacion() {
	}

	public RecursoInstalacion(int idRecursoInstalacion,
			Instalacion instalacion, Recurso recurso, short cantidad) {
		this.idRecursoInstalacion = idRecursoInstalacion;
		this.instalacion = instalacion;
		this.recurso = recurso;
		this.cantidad = cantidad;
	}

	public int getIdRecursoInstalacion() {
		return this.idRecursoInstalacion;
	}

	public void setIdRecursoInstalacion(int idRecursoInstalacion) {
		this.idRecursoInstalacion = idRecursoInstalacion;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

	public short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(short cantidad) {
		this.cantidad = cantidad;
	}

}
