package modelos;

// Generated 26/02/2016 11:27:56 AM by Hibernate Tools 4.3.1

/**
 * RecursoInstalacion generated by hbm2java
 */
public class RecursoInstalacion implements java.io.Serializable {

	private int idRecursoInstalacion;
	private Instalacion instalacion;
	private Recurso recurso;
	private int cantidad;
	private boolean activo;

	public RecursoInstalacion() {
	}

	public RecursoInstalacion(int idRecursoInstalacion,
			Instalacion instalacion, Recurso recurso, int cantidad,
			boolean activo) {
		this.idRecursoInstalacion = idRecursoInstalacion;
		this.instalacion = instalacion;
		this.recurso = recurso;
		this.cantidad = cantidad;
		this.activo = activo;
	}

	public int getIdRecursoInstalacion() {
		return this.idRecursoInstalacion;
	}

	public void setIdRecursoInstalacion(int idRecursoInstalacion) {
		this.idRecursoInstalacion = idRecursoInstalacion;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
