package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

/**
 * RedClub generated by hbm2java
 */
public class RedClub implements java.io.Serializable {

	private int idRedClub;
	private Club club;
	private RedSocial redSocial;
	private String enlace;

	public RedClub() {
	}

	public RedClub(int idRedClub, Club club, String enlace) {
		this.idRedClub = idRedClub;
		this.club = club;
		this.enlace = enlace;
	}

	public RedClub(int idRedClub, Club club, RedSocial redSocial, String enlace) {
		this.idRedClub = idRedClub;
		this.club = club;
		this.redSocial = redSocial;
		this.enlace = enlace;
	}

	public int getIdRedClub() {
		return this.idRedClub;
	}

	public void setIdRedClub(int idRedClub) {
		this.idRedClub = idRedClub;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public RedSocial getRedSocial() {
		return this.redSocial;
	}

	public void setRedSocial(RedSocial redSocial) {
		this.redSocial = redSocial;
	}

	public String getEnlace() {
		return this.enlace;
	}

	public void setEnlace(String enlace) {
		this.enlace = enlace;
	}

}
