package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

/**
 * RedPersona generated by hbm2java
 */
public class RedPersona implements java.io.Serializable {

	private int idRedPersona;
	private Persona persona;
	private RedSocial redSocial;
	private String enlace;

	public RedPersona() {
	}

	public RedPersona(int idRedPersona, Persona persona, RedSocial redSocial,
			String enlace) {
		this.idRedPersona = idRedPersona;
		this.persona = persona;
		this.redSocial = redSocial;
		this.enlace = enlace;
	}

	public int getIdRedPersona() {
		return this.idRedPersona;
	}

	public void setIdRedPersona(int idRedPersona) {
		this.idRedPersona = idRedPersona;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public RedSocial getRedSocial() {
		return this.redSocial;
	}

	public void setRedSocial(RedSocial redSocial) {
		this.redSocial = redSocial;
	}

	public String getEnlace() {
		return this.enlace;
	}

	public void setEnlace(String enlace) {
		this.enlace = enlace;
	}

}
