package modelos;

import java.text.SimpleDateFormat;

// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import util.Format;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion implements java.io.Serializable {

	private int idReservacion;
	private Instalacion instalacion;
	private Socio socio;
	private Date fechaInicio;
	private Date fechaFin;
	private char condicion;
	private boolean activo = true;
	private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);
	private Set<CalendarioFecha> calendarioFechas = new HashSet<CalendarioFecha>(
			0);

	public Reservacion() {
	}

	public Reservacion(int idReservacion, Instalacion instalacion, Socio socio,
			Date fechaInicio, Date fechaFin, boolean activo) {
		this.idReservacion = idReservacion;
		this.instalacion = instalacion;
		this.socio = socio;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.activo = activo;
	}

	public Reservacion(int idReservacion, Instalacion instalacion, Socio socio,
			Date fechaInicio, Date fechaFin, char condicion, boolean activo,
			Set<Alquiler> alquilers, Set<CalendarioFecha> calendarioFechas) {
		this.idReservacion = idReservacion;
		this.instalacion = instalacion;
		this.socio = socio;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.condicion = condicion;
		this.activo = activo;
		this.alquilers = alquilers;
		this.calendarioFechas = calendarioFechas;
	}

	public int getIdReservacion() {
		return this.idReservacion;
	}

	public void setIdReservacion(int idReservacion) {
		this.idReservacion = idReservacion;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public char getCondicion() {
		return this.condicion;
	}

	public void setCondicion(char condicion) {
		this.condicion = condicion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Alquiler> getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set<Alquiler> alquilers) {
		this.alquilers = alquilers;
	}

	public Set<CalendarioFecha> getCalendarioFechas() {
		return this.calendarioFechas;
	}

	public void setCalendarioFechas(Set<CalendarioFecha> calendarioFechas) {
		this.calendarioFechas = calendarioFechas;
	}
	
	//Metodos Que no se pueden borrar 
	public String getFechaInicioString(){
		return Format.getDateString(fechaInicio);
	}
	
	public String getFechaFinString(){		
		return Format.getDateString(fechaFin);
	}
	
	public String getHoraInicioString(){
		return Format.getTimeString(fechaInicio);
	}
	
	public String getHoraFinString(){		
		return Format.getTimeString(fechaFin);
	}


}
