package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion implements java.io.Serializable {

	private int idReservacion;
	private Instalacion instalacion;
	private Socio socio;
	private Date fechaInicio;
	private Date horaInic;
	private Date horaFin;
	private short fechaFin;
	private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);
	private Set<CalendarioFecha> calendarioFechas = new HashSet<CalendarioFecha>(
			0);

	public Reservacion() {
	}

	public Reservacion(int idReservacion, Instalacion instalacion, Socio socio,
			Date fechaInicio, Date horaInic, Date horaFin, short fechaFin) {
		this.idReservacion = idReservacion;
		this.instalacion = instalacion;
		this.socio = socio;
		this.fechaInicio = fechaInicio;
		this.horaInic = horaInic;
		this.horaFin = horaFin;
		this.fechaFin = fechaFin;
	}

	public Reservacion(int idReservacion, Instalacion instalacion, Socio socio,
			Date fechaInicio, Date horaInic, Date horaFin, short fechaFin,
			Set<Alquiler> alquilers, Set<CalendarioFecha> calendarioFechas) {
		this.idReservacion = idReservacion;
		this.instalacion = instalacion;
		this.socio = socio;
		this.fechaInicio = fechaInicio;
		this.horaInic = horaInic;
		this.horaFin = horaFin;
		this.fechaFin = fechaFin;
		this.alquilers = alquilers;
		this.calendarioFechas = calendarioFechas;
	}

	public int getIdReservacion() {
		return this.idReservacion;
	}

	public void setIdReservacion(int idReservacion) {
		this.idReservacion = idReservacion;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getHoraInic() {
		return this.horaInic;
	}

	public void setHoraInic(Date horaInic) {
		this.horaInic = horaInic;
	}

	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	public short getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(short fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Set<Alquiler> getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set<Alquiler> alquilers) {
		this.alquilers = alquilers;
	}

	public Set<CalendarioFecha> getCalendarioFechas() {
		return this.calendarioFechas;
	}

	public void setCalendarioFechas(Set<CalendarioFecha> calendarioFechas) {
		this.calendarioFechas = calendarioFechas;
	}

}
