package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio implements java.io.Serializable {

	private int idSocio;
	private Persona persona;
	private Postulacion postulacion;
	private String nroCarnet;
	private Set<Sancion> sancions = new HashSet<Sancion>(0);
	private Set<Visita> visitas = new HashSet<Visita>(0);
	private Set<Accion> accions = new HashSet<Accion>(0);
	private Set<Desvinculacion> desvinculacions = new HashSet<Desvinculacion>(0);
	private Set<Reservacion> reservacions = new HashSet<Reservacion>(0);
	private Set<Afiliado> afiliados = new HashSet<Afiliado>(0);
	private Set<SolicitudEvento> solicitudEventos = new HashSet<SolicitudEvento>(
			0);

	public Socio() {
	}

	public Socio(int idSocio, Persona persona, String nroCarnet) {
		this.idSocio = idSocio;
		this.persona = persona;
		this.nroCarnet = nroCarnet;
	}

	public Socio(int idSocio, Persona persona, Postulacion postulacion,
			String nroCarnet, Set<Sancion> sancions, Set<Visita> visitas,
			Set<Accion> accions, Set<Desvinculacion> desvinculacions,
			Set<Reservacion> reservacions, Set<Afiliado> afiliados,
			Set<SolicitudEvento> solicitudEventos) {
		this.idSocio = idSocio;
		this.persona = persona;
		this.postulacion = postulacion;
		this.nroCarnet = nroCarnet;
		this.sancions = sancions;
		this.visitas = visitas;
		this.accions = accions;
		this.desvinculacions = desvinculacions;
		this.reservacions = reservacions;
		this.afiliados = afiliados;
		this.solicitudEventos = solicitudEventos;
	}

	public int getIdSocio() {
		return this.idSocio;
	}

	public void setIdSocio(int idSocio) {
		this.idSocio = idSocio;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Postulacion getPostulacion() {
		return this.postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	public String getNroCarnet() {
		return this.nroCarnet;
	}

	public void setNroCarnet(String nroCarnet) {
		this.nroCarnet = nroCarnet;
	}

	public Set<Sancion> getSancions() {
		return this.sancions;
	}

	public void setSancions(Set<Sancion> sancions) {
		this.sancions = sancions;
	}

	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

	public Set<Accion> getAccions() {
		return this.accions;
	}

	public void setAccions(Set<Accion> accions) {
		this.accions = accions;
	}

	public Set<Desvinculacion> getDesvinculacions() {
		return this.desvinculacions;
	}

	public void setDesvinculacions(Set<Desvinculacion> desvinculacions) {
		this.desvinculacions = desvinculacions;
	}

	public Set<Reservacion> getReservacions() {
		return this.reservacions;
	}

	public void setReservacions(Set<Reservacion> reservacions) {
		this.reservacions = reservacions;
	}

	public Set<Afiliado> getAfiliados() {
		return this.afiliados;
	}

	public void setAfiliados(Set<Afiliado> afiliados) {
		this.afiliados = afiliados;
	}

	public Set<SolicitudEvento> getSolicitudEventos() {
		return this.solicitudEventos;
	}

	public void setSolicitudEventos(Set<SolicitudEvento> solicitudEventos) {
		this.solicitudEventos = solicitudEventos;
	}

}
