package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SolicitudEvento generated by hbm2java
 */
public class SolicitudEvento implements java.io.Serializable {

	private int idSolicitudEvento;
	private Socio socio;
	private Date fechaEvento;
	private String descripcion;
	private Date fechaSolicitud;
	private Set<EstadoSolicitud> estadoSolicituds = new HashSet<EstadoSolicitud>(
			0);

	public SolicitudEvento() {
	}

	public SolicitudEvento(int idSolicitudEvento, Socio socio,
			String descripcion, Date fechaSolicitud) {
		this.idSolicitudEvento = idSolicitudEvento;
		this.socio = socio;
		this.descripcion = descripcion;
		this.fechaSolicitud = fechaSolicitud;
	}

	public SolicitudEvento(int idSolicitudEvento, Socio socio,
			Date fechaEvento, String descripcion, Date fechaSolicitud,
			Set<EstadoSolicitud> estadoSolicituds) {
		this.idSolicitudEvento = idSolicitudEvento;
		this.socio = socio;
		this.fechaEvento = fechaEvento;
		this.descripcion = descripcion;
		this.fechaSolicitud = fechaSolicitud;
		this.estadoSolicituds = estadoSolicituds;
	}

	public int getIdSolicitudEvento() {
		return this.idSolicitudEvento;
	}

	public void setIdSolicitudEvento(int idSolicitudEvento) {
		this.idSolicitudEvento = idSolicitudEvento;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Date getFechaEvento() {
		return this.fechaEvento;
	}

	public void setFechaEvento(Date fechaEvento) {
		this.fechaEvento = fechaEvento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	public Set<EstadoSolicitud> getEstadoSolicituds() {
		return this.estadoSolicituds;
	}

	public void setEstadoSolicituds(Set<EstadoSolicitud> estadoSolicituds) {
		this.estadoSolicituds = estadoSolicituds;
	}

}
