package modelos;

// Generated 26/02/2016 11:27:56 AM by Hibernate Tools 4.3.1

/**
 * SolicitudVenta generated by hbm2java
 */
public class SolicitudVenta implements java.io.Serializable {

	private int idSolicitudVenta;
	private Accion accion;
	private String motivo;
	private boolean activo;

	public SolicitudVenta() {
	}

	public SolicitudVenta(int idSolicitudVenta, Accion accion, String motivo,
			boolean activo) {
		this.idSolicitudVenta = idSolicitudVenta;
		this.accion = accion;
		this.motivo = motivo;
		this.activo = activo;
	}

	public int getIdSolicitudVenta() {
		return this.idSolicitudVenta;
	}

	public void setIdSolicitudVenta(int idSolicitudVenta) {
		this.idSolicitudVenta = idSolicitudVenta;
	}

	public Accion getAccion() {
		return this.accion;
	}

	public void setAccion(Accion accion) {
		this.accion = accion;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
