package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Sugerencia generated by hbm2java
 */
public class Sugerencia implements java.io.Serializable {

	private int idSugerencia;
	private ClienteExterno clienteExterno;
	private TipoSugerencia tipoSugerencia;
	private Usuario usuario;
	private String descripcion;
	private Date fecha;

	public Sugerencia() {
	}

	public Sugerencia(int idSugerencia, TipoSugerencia tipoSugerencia,
			String descripcion, Date fecha) {
		this.idSugerencia = idSugerencia;
		this.tipoSugerencia = tipoSugerencia;
		this.descripcion = descripcion;
		this.fecha = fecha;
	}

	public Sugerencia(int idSugerencia, ClienteExterno clienteExterno,
			TipoSugerencia tipoSugerencia, Usuario usuario, String descripcion,
			Date fecha) {
		this.idSugerencia = idSugerencia;
		this.clienteExterno = clienteExterno;
		this.tipoSugerencia = tipoSugerencia;
		this.usuario = usuario;
		this.descripcion = descripcion;
		this.fecha = fecha;
	}

	public int getIdSugerencia() {
		return this.idSugerencia;
	}

	public void setIdSugerencia(int idSugerencia) {
		this.idSugerencia = idSugerencia;
	}

	public ClienteExterno getClienteExterno() {
		return this.clienteExterno;
	}

	public void setClienteExterno(ClienteExterno clienteExterno) {
		this.clienteExterno = clienteExterno;
	}

	public TipoSugerencia getTipoSugerencia() {
		return this.tipoSugerencia;
	}

	public void setTipoSugerencia(TipoSugerencia tipoSugerencia) {
		this.tipoSugerencia = tipoSugerencia;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
