package modelos;

// Generated 14/02/2016 02:21:08 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoActividad generated by hbm2java
 */
public class TipoActividad implements java.io.Serializable {

	private int idTipoActividad;
	private String descripcion;
	private Set<Actividad> actividads = new HashSet<Actividad>(0);

	public TipoActividad() {
	}

	public TipoActividad(int idTipoActividad, String descripcion) {
		this.idTipoActividad = idTipoActividad;
		this.descripcion = descripcion;
	}

	public TipoActividad(int idTipoActividad, String descripcion,
			Set<Actividad> actividads) {
		this.idTipoActividad = idTipoActividad;
		this.descripcion = descripcion;
		this.actividads = actividads;
	}

	public int getIdTipoActividad() {
		return this.idTipoActividad;
	}

	public void setIdTipoActividad(int idTipoActividad) {
		this.idTipoActividad = idTipoActividad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(Set<Actividad> actividads) {
		this.actividads = actividads;
	}

}
