package modelos;

// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago implements java.io.Serializable {

	private int idTipoPago;
	private String descripcion;
	private boolean activo = true;
	private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);

	public TipoPago() {
	}

	public TipoPago(int idTipoPago, String descripcion, boolean activo) {
		this.idTipoPago = idTipoPago;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public TipoPago(int idTipoPago, String descripcion, boolean activo,
			Set<Alquiler> alquilers) {
		this.idTipoPago = idTipoPago;
		this.descripcion = descripcion;
		this.activo = activo;
		this.alquilers = alquilers;
	}

	public int getIdTipoPago() {
		return this.idTipoPago;
	}

	public void setIdTipoPago(int idTipoPago) {
		this.idTipoPago = idTipoPago;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Alquiler> getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set<Alquiler> alquilers) {
		this.alquilers = alquilers;
	}

}
