package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoEvento generated by hbm2java
 */
public class TipoEvento implements java.io.Serializable {

	private int idTipoEvento;
	private short descripcion;
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public TipoEvento() {
	}

	public TipoEvento(int idTipoEvento, short descripcion) {
		this.idTipoEvento = idTipoEvento;
		this.descripcion = descripcion;
	}

	public TipoEvento(int idTipoEvento, short descripcion, Set<Evento> eventos) {
		this.idTipoEvento = idTipoEvento;
		this.descripcion = descripcion;
		this.eventos = eventos;
	}

	public int getIdTipoEvento() {
		return this.idTipoEvento;
	}

	public void setIdTipoEvento(int idTipoEvento) {
		this.idTipoEvento = idTipoEvento;
	}

	public short getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(short descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
