package modelos;

// Generated 18/02/2016 10:39:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoSugerencia generated by hbm2java
 */
public class TipoSugerencia implements java.io.Serializable {

	private int idTipoSugerencia;
	private String descripcion;
	private Set<Sugerencia> sugerencias = new HashSet<Sugerencia>(0);

	public TipoSugerencia() {
	}

	public TipoSugerencia(int idTipoSugerencia, String descripcion) {
		this.idTipoSugerencia = idTipoSugerencia;
		this.descripcion = descripcion;
	}

	public TipoSugerencia(int idTipoSugerencia, String descripcion,
			Set<Sugerencia> sugerencias) {
		this.idTipoSugerencia = idTipoSugerencia;
		this.descripcion = descripcion;
		this.sugerencias = sugerencias;
	}

	public int getIdTipoSugerencia() {
		return this.idTipoSugerencia;
	}

	public void setIdTipoSugerencia(int idTipoSugerencia) {
		this.idTipoSugerencia = idTipoSugerencia;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Sugerencia> getSugerencias() {
		return this.sugerencias;
	}

	public void setSugerencias(Set<Sugerencia> sugerencias) {
		this.sugerencias = sugerencias;
	}

}
