package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoAfiliado generated by hbm2java
 */
public class TipoAfiliado implements java.io.Serializable {

	private int idTipoAfiliado;
	private String descripcion;
	private Set<Afiliado> afiliados = new HashSet<Afiliado>(0);

	public TipoAfiliado() {
	}

	public TipoAfiliado(int idTipoAfiliado, String descripcion) {
		this.idTipoAfiliado = idTipoAfiliado;
		this.descripcion = descripcion;
	}

	public TipoAfiliado(int idTipoAfiliado, String descripcion,
			Set<Afiliado> afiliados) {
		this.idTipoAfiliado = idTipoAfiliado;
		this.descripcion = descripcion;
		this.afiliados = afiliados;
	}

	public int getIdTipoAfiliado() {
		return this.idTipoAfiliado;
	}

	public void setIdTipoAfiliado(int idTipoAfiliado) {
		this.idTipoAfiliado = idTipoAfiliado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Afiliado> getAfiliados() {
		return this.afiliados;
	}

	public void setAfiliados(Set<Afiliado> afiliados) {
		this.afiliados = afiliados;
	}

}
