package modelos;

// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoSancion generated by hbm2java
 */
public class TipoSancion implements java.io.Serializable {

	private int idTipoSancion;
	private String descripcion;
	private boolean activo = true;
	private Set<Sancion> sancions = new HashSet<Sancion>(0);

	public TipoSancion() {
	}

	public TipoSancion(int idTipoSancion, String descripcion, boolean activo) {
		this.idTipoSancion = idTipoSancion;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public TipoSancion(int idTipoSancion, String descripcion, boolean activo,
			Set<Sancion> sancions) {
		this.idTipoSancion = idTipoSancion;
		this.descripcion = descripcion;
		this.activo = activo;
		this.sancions = sancions;
	}

	public int getIdTipoSancion() {
		return this.idTipoSancion;
	}

	public void setIdTipoSancion(int idTipoSancion) {
		this.idTipoSancion = idTipoSancion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Sancion> getSancions() {
		return this.sancions;
	}

	public void setSancions(Set<Sancion> sancions) {
		this.sancions = sancions;
	}

}
