package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

/**
 * UsuarioGrupo generated by hbm2java
 */
public class UsuarioGrupo implements java.io.Serializable {

	private int idUsuarioGrupo;
	private Grupo grupo;
	private Usuario usuario;

	public UsuarioGrupo() {
	}

	public UsuarioGrupo(int idUsuarioGrupo, Grupo grupo, Usuario usuario) {
		this.idUsuarioGrupo = idUsuarioGrupo;
		this.grupo = grupo;
		this.usuario = usuario;
	}

	public int getIdUsuarioGrupo() {
		return this.idUsuarioGrupo;
	}

	public void setIdUsuarioGrupo(int idUsuarioGrupo) {
		this.idUsuarioGrupo = idUsuarioGrupo;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
