package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int idUsuario;
	private Persona persona;
	private String contrasenna;
	private String username;
	private String pregunta;
	private String respuesta;
	private Date fecha;
	private Set<UsuarioGrupo> usuarioGrupos = new HashSet<UsuarioGrupo>(0);
	private Set<Opinion> opinions = new HashSet<Opinion>(0);
	private Set<Sugerencia> sugerencias = new HashSet<Sugerencia>(0);

	public Usuario() {
	}

	public Usuario(int idUsuario, Persona persona, String contrasenna,
			String username, String pregunta, String respuesta, Date fecha) {
		this.idUsuario = idUsuario;
		this.persona = persona;
		this.contrasenna = contrasenna;
		this.username = username;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
		this.fecha = fecha;
	}

	public Usuario(int idUsuario, Persona persona, String contrasenna,
			String username, String pregunta, String respuesta, Date fecha,
			Set<UsuarioGrupo> usuarioGrupos, Set<Opinion> opinions,
			Set<Sugerencia> sugerencias) {
		this.idUsuario = idUsuario;
		this.persona = persona;
		this.contrasenna = contrasenna;
		this.username = username;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
		this.fecha = fecha;
		this.usuarioGrupos = usuarioGrupos;
		this.opinions = opinions;
		this.sugerencias = sugerencias;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public String getContrasenna() {
		return this.contrasenna;
	}

	public void setContrasenna(String contrasenna) {
		this.contrasenna = contrasenna;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set<UsuarioGrupo> getUsuarioGrupos() {
		return this.usuarioGrupos;
	}

	public void setUsuarioGrupos(Set<UsuarioGrupo> usuarioGrupos) {
		this.usuarioGrupos = usuarioGrupos;
	}

	public Set<Opinion> getOpinions() {
		return this.opinions;
	}

	public void setOpinions(Set<Opinion> opinions) {
		this.opinions = opinions;
	}

	public Set<Sugerencia> getSugerencias() {
		return this.sugerencias;
	}

	public void setSugerencias(Set<Sugerencia> sugerencias) {
		this.sugerencias = sugerencias;
	}

}
