package modelos;

// Generated 07/02/2016 10:09:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Visita generated by hbm2java
 */
public class Visita implements java.io.Serializable {

	private int idVisita;
	private Afiliado afiliado;
	private Invitado invitado;
	private Socio socio;
	private Date fecha;
	private boolean externo;
	private Set<VisitaEvento> visitaEventos = new HashSet<VisitaEvento>(0);

	public Visita() {
	}

	public Visita(int idVisita, Date fecha, boolean externo) {
		this.idVisita = idVisita;
		this.fecha = fecha;
		this.externo = externo;
	}

	public Visita(int idVisita, Afiliado afiliado, Invitado invitado,
			Socio socio, Date fecha, boolean externo,
			Set<VisitaEvento> visitaEventos) {
		this.idVisita = idVisita;
		this.afiliado = afiliado;
		this.invitado = invitado;
		this.socio = socio;
		this.fecha = fecha;
		this.externo = externo;
		this.visitaEventos = visitaEventos;
	}

	public int getIdVisita() {
		return this.idVisita;
	}

	public void setIdVisita(int idVisita) {
		this.idVisita = idVisita;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public Invitado getInvitado() {
		return this.invitado;
	}

	public void setInvitado(Invitado invitado) {
		this.invitado = invitado;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean isExterno() {
		return this.externo;
	}

	public void setExterno(boolean externo) {
		this.externo = externo;
	}

	public Set<VisitaEvento> getVisitaEventos() {
		return this.visitaEventos;
	}

	public void setVisitaEventos(Set<VisitaEvento> visitaEventos) {
		this.visitaEventos = visitaEventos;
	}

}
